---
title: "GAF to Go"
output: html_document
date: "2024-12-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/stor/work/Hofmann/All_projects/P_lethostigma_Feeding_Study/R_work/GAF_to_GO")
```


Load libraries:
```{r}
#library(rjson)
library(tidyverse)
library(tidyjson)
```


before loading file, remove ! lines first, except header line, for which you must remove the !# before <DB	GeneID	Symbol	Qualifier	GO_ID	Reference	Evidence_Code	With,From	Aspect	Gene_Name	Gene_Synonym	Type	Taxon	Date	Assigned_By	Annot_Ext	Gene_Product_Form_ID>
```{r}
gaf_file <- read.delim("GCF_001970005.1_Flounder_ref_guided_V1.0_gene_ontology_edited.gaf", header = TRUE)
```

Read in GO json file from https://geneontology.org/docs/download-ontology/ e.g. 

wget https://purl.obolibrary.org/obo/go.json in the console

```{r}
GO_json <- read_json("./go.json")
```

```{r}
GO_json %>% spread_all
```



```{r}
GO_json %>% enter_object(graphs) %>% gather_array
```

```{r}
GO_json %>% enter_object(graphs) %>% gather_array %>%  spread_all 
```

```{r}
GO_df <- GO_json %>% enter_object(graphs) %>% gather_array %>% 
  enter_object(nodes) %>% gather_array %>%
  spread_all %>% select(id, type, lbl, meta.definition.val )
```



```{r}
dim(GO_df)
head(GO_df)

GO_dataframe <- data.frame(GO_df[, 1:5])
dim(GO_dataframe)
head(GO_dataframe)
```


```{r}
GO_json_dataframe <- data.frame(GO_df[, 1:5]) %>%
  separate_wider_delim(id, delim = "/",  names = c( NA,NA,NA,NA, "GO_ID")) %>%
  mutate(GO_ID = gsub("_", ":", GO_ID))
```

```{r}
GO_dataframe <- data.frame(GO_json_dataframe[, 1:4])
str(GO_dataframe)

dim(GO_dataframe)
dim(gaf_file)
```



```{r}
colnames(GO_dataframe)
colnames(gaf_file)

dim(GO_dataframe)
dim(gaf_file)

gaf_GO <- merge(gaf_file, GO_dataframe, by = "GO_ID" )
dim(gaf_GO)
```
```{r}
write.csv( gaf_GO, file = "GCF_001970005.1_Flounder_ref_guided_V1.0_GAF_with_GO.csv")
```


